_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    NAME: build_resnest_backbone

  HEADS:
    CLS_LAYER: arcFace
    POOL_LAYER: gempool

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True
  CA:
    PROB: 0.5
    ENABLED: False
  LI:
    ENABLED: True
    ALPHA: 0.1

DATASETS:
  NAMES: ("NAICReID:0910","NAIC19_REP:1010","NAICReID_REP:0910")
  TESTS: ("NAICReID_REP:0910",)

DATALOADER:
  PK_SAMPLER: True
  NAIVE_WAY: False
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
SOLVER:
  OPT: "Ranger"
  AMP: True
  CHECKPOINT_PERIOD: 2
  STEPS: [40, 80 , 100]
  IMS_PER_BATCH: 256
TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "logs/NAICREP/R101-ibn-arcF-cj-lighting-st-amp-gem-all-ranger2-bs256-balance-384x128"
