_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

INPUT:
  DO_GRAYSCALE: True

OUTPUT_DIR: "logs/HIT/bagtricks_R101-ibn-gray"

TEST:
  AQE:
    ALPHA: 3.0
    ENABLED: False
    QE_K: 5
    QE_TIME: 1
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 256