_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

INPUT:
  DO_GRAYSCALE: True

OUTPUT_DIR: "logs/HIT/bagtricks_R101-ibn"
