_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "x0_75"
    WITH_IBN: False
    NAME: build_resnest_backbone

  HEADS:
    NAME: "ProtoneckHead"
    IN_FEAT: 384
    CLS_LAYER: arcFace
    POOL_LAYER: gempool


INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID:0910","NAIC19_REP:1010")
  TESTS: ("NAICReID:0910",)

SOLVER:
  OPT: "Ranger"
  AMP: True
  CHECKPOINT_PERIOD: 2
  STEPS: [40, 90]
  IMS_PER_BATCH: 128

TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "logs/NAIC/R101-ibn-arcF-cj-osnet75-amp-gem-all-ranger2-protonet"