_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: build_efficientnet_backbone
    MODEL_NAME: efficientnet-b5

  HEADS:
    CLS_LAYER: arcFace
    POOL_LAYER: avgpool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

SOLVER:
  IMS_PER_BATCH: 128

TEST:
  EVAL_PERIOD: 2

DATASETS:
  NAMES: ("NAICReID:0910","NAIC19_REP:1010")
  TESTS: ("NAICReID:0910",)

OUTPUT_DIR: "logs/HIT/sb-EFN5-arcF-cj-19"
