_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 1.0
    TRI:
      MARGIN: 0.5

DATALOADER:
  NUM_INSTANCE: 8

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

OUTPUT_DIR: "logs/NAIC/bagtricks_R101-ibn-i8-05"
