_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

INPUT:
  CT:
    ENABLED: True


OUTPUT_DIR: "logs/NAIC/bagtricks_R101-ibn-ct"
