_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

  HEADS:
    CLS_LAYER: arcSoftmax

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

OUTPUT_DIR: "logs/NAIC/bagtricks_R101-ibn-aS"
