_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "x1_0"
    WITH_IBN: True
    NAME: build_osnet_backbone

  HEADS:
    IN_FEAT: 512
    CLS_LAYER: arcFace
    POOL_LAYER: gempool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID:0910","NAIC19_REP:1010")
  TESTS: ("NAICReID:0910",)

SOLVER:
  OPT: "Ranger"
  AMP: True
  CHECKPOINT_PERIOD: 2
  STEPS: [40, 90]
  IMS_PER_BATCH: 128

TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "logs/NAIC/R101-ibn-arcF-cj-osnetx1_0-amp-gem-all-ranger2"