_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    NAME: build_resnest_backbone

  HEADS:
    CLS_LAYER: arcFace
    POOL_LAYER: gempool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID:1010","NAIC19_REP:0809")
  TESTS: ("NAIC19_REP:0809",)

SOLVER:
  OPT: "Ranger"
  AMP: True
  CHECKPOINT_PERIOD: 2
  STEPS: [40, 90]
  SWA:
    ENABLED: True
TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "logs/NAIC/R101-ibn-arcF-cj-st-amp-gem-all-ranger-swa"
