_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True

  HEADS:
    CLS_LAYER: circleSoftmax
    POOL_LAYER: avgmaxpool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

OUTPUT_DIR: "logs/NAIC/R101-ibn-cS-cj-amp"
