_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    NAME: build_resnest_backbone

  HEADS:
    CLS_LAYER: adaCos
    POOL_LAYER: avgpool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAIC19Test",)

OUTPUT_DIR: "logs/NAIC/R101-ibn-adaC-cj-st"
