_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    NAME: build_resnest_backbone
    RECTIFIED_CONV: True

  HEADS:
    CLS_LAYER: arcFace
    POOL_LAYER: gempool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID","NAIC19_REP")
  TESTS: ("NAIC19_REP",)

SOLVER:
  AMP: False
  CHECKPOINT_PERIOD: 2
  IMS_PER_BATCH: 64
TEST:
  EVAL_PERIOD: 2

OUTPUT_DIR: "logs/NAIC/R101-ibn-arcF-cj-st-amp-gem-all-rfconv"
