_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "101x"
    WITH_IBN: True
    WITH_NL: True
    NAME: build_resnest_backbone

  HEADS:
    CLS_LAYER: cosFace
    POOL_LAYER: avgpool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

SOLVER:
  AMP: True


OUTPUT_DIR: "logs/NAIC/R101-ibn-cosF-cj-st-amp-nl"
