_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    NAME: build_efficientnet_backbone
    MODEL_NAME: efficientnet-b5

  HEADS:
    CLS_LAYER: circleSoftmax
    POOL_LAYER: avgpool

INPUT:
  REA:
    ENABLED: false

  CJ:
    PROB: 0.5
    ENABLED: True

SOLVER:
  IMS_PER_BATCH: 32


DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

OUTPUT_DIR: "logs/NAIC/R101-ibn-cS-cj-efn5"
