_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: "50x"
    WITH_IBN: True

  LOSSES:
    NAME: ("FocalLoss", "CircleLoss",)
    FL:
      SCALE: 1.0
    CIRCLE:
      MARGIN: 0.5

DATASETS:
  NAMES: ("NAICReID",)
  TESTS: ("NAICReID",)

INPUT:
  CT:
    ENABLED: False

SOLVER:
  SWA:
    ENABLED: True


OUTPUT_DIR: "logs/NAIC/strong_R50-ibn-swa-fl-cl"
